-- MySQL Script generated by MySQL Workbench
-- ds 17 feb 2018 16:02:17 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema miod
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema miod
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `miod` DEFAULT CHARACTER SET utf8 ;
USE `miod` ;

-- -----------------------------------------------------
-- Table `miod`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miod`.`Location` (
  `idLocation` INT NOT NULL,
  `StartGRCh38` VARCHAR(45) NULL,
  `EndGRCh38` VARCHAR(45) NULL,
  `Chromosome` VARCHAR(45) NULL,
  `Strand` VARCHAR(45) NULL,
  PRIMARY KEY (`idLocation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miod`.`Gene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miod`.`Gene` (
  `idGene` INT NOT NULL AUTO_INCREMENT,
  `GeneName` VARCHAR(45) NULL,
  `idENSEMBL` VARCHAR(45) NULL,
  `Location_idLocation` INT NOT NULL,
  PRIMARY KEY (`idGene`, `Location_idLocation`),
  INDEX `fk_Gene_Location_idx` (`Location_idLocation` ASC),
  CONSTRAINT `fk_Gene_Location`
    FOREIGN KEY (`Location_idLocation`)
    REFERENCES `miod`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miod`.`ClinicalSignificance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miod`.`ClinicalSignificance` (
  `idClinicalSignificance` INT NOT NULL,
  `Value` VARCHAR(45) NULL,
  PRIMARY KEY (`idClinicalSignificance`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miod`.`Disease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miod`.`Disease` (
  `idDisease` INT NOT NULL,
  `DiseaseName` VARCHAR(45) NULL,
  `idMIM` VARCHAR(45) NULL,
  PRIMARY KEY (`idDisease`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miod`.`Reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miod`.`Reference` (
  `idReference` INT NOT NULL,
  `PMID` TEXT NULL,
  `DB` VARCHAR(45) NULL,
  PRIMARY KEY (`idReference`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miod`.`Microindel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miod`.`Microindel` (
  `idMicroindel` INT NOT NULL,
  `Info` TEXT NULL,
  `Name` VARCHAR(45) NULL,
  `Location_idLocation` INT NOT NULL,
  PRIMARY KEY (`idMicroindel`, `Location_idLocation`),
  INDEX `fk_Microindel_Location1_idx` (`Location_idLocation` ASC),
  CONSTRAINT `fk_Microindel_Location1`
    FOREIGN KEY (`Location_idLocation`)
    REFERENCES `miod`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miod`.`Microindel_has_Reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miod`.`Microindel_has_Reference` (
  `Microindel_idMicroindel` INT NOT NULL,
  `Reference_idReference` INT NOT NULL,
  PRIMARY KEY (`Microindel_idMicroindel`, `Reference_idReference`),
  INDEX `fk_Microindel_has_Reference_Reference1_idx` (`Reference_idReference` ASC),
  INDEX `fk_Microindel_has_Reference_Microindel1_idx` (`Microindel_idMicroindel` ASC),
  CONSTRAINT `fk_Microindel_has_Reference_Microindel1`
    FOREIGN KEY (`Microindel_idMicroindel`)
    REFERENCES `miod`.`Microindel` (`idMicroindel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Microindel_has_Reference_Reference1`
    FOREIGN KEY (`Reference_idReference`)
    REFERENCES `miod`.`Reference` (`idReference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miod`.`Microindel_has_ClinicalSignificance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miod`.`Microindel_has_ClinicalSignificance` (
  `Microindel_idMicroindel` INT NOT NULL,
  `ClinicalSignificance_idClinicalSignificance` INT NOT NULL,
  PRIMARY KEY (`Microindel_idMicroindel`, `ClinicalSignificance_idClinicalSignificance`),
  INDEX `fk_Microindel_has_ClinicalSignificance_ClinicalSignificance_idx` (`ClinicalSignificance_idClinicalSignificance` ASC),
  INDEX `fk_Microindel_has_ClinicalSignificance_Microindel1_idx` (`Microindel_idMicroindel` ASC),
  CONSTRAINT `fk_Microindel_has_ClinicalSignificance_Microindel1`
    FOREIGN KEY (`Microindel_idMicroindel`)
    REFERENCES `miod`.`Microindel` (`idMicroindel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Microindel_has_ClinicalSignificance_ClinicalSignificance1`
    FOREIGN KEY (`ClinicalSignificance_idClinicalSignificance`)
    REFERENCES `miod`.`ClinicalSignificance` (`idClinicalSignificance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miod`.`Microindel_has_Disease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miod`.`Microindel_has_Disease` (
  `Microindel_idMicroindel` INT NOT NULL,
  `Disease_idDisease` INT NOT NULL,
  PRIMARY KEY (`Microindel_idMicroindel`, `Disease_idDisease`),
  INDEX `fk_Microindel_has_Disease_Disease1_idx` (`Disease_idDisease` ASC),
  INDEX `fk_Microindel_has_Disease_Microindel1_idx` (`Microindel_idMicroindel` ASC),
  CONSTRAINT `fk_Microindel_has_Disease_Microindel1`
    FOREIGN KEY (`Microindel_idMicroindel`)
    REFERENCES `miod`.`Microindel` (`idMicroindel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Microindel_has_Disease_Disease1`
    FOREIGN KEY (`Disease_idDisease`)
    REFERENCES `miod`.`Disease` (`idDisease`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
