-- MySQL Script generated by MySQL Workbench
-- dc 21 feb 2018 10:46:31 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema miod
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema miod
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `miod` DEFAULT CHARACTER SET utf8 ;
USE `miod` ;

-- -----------------------------------------------------
-- Table `miod`.`Gene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miod`.`Gene` (
  `idGene` INT NOT NULL AUTO_INCREMENT,
  `GeneName` VARCHAR(45) NULL,
  `idENSEMBL` VARCHAR(45) NULL,
  PRIMARY KEY (`idGene`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miod`.`Chromosome`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miod`.`Chromosome` (
  `idChromosome` INT NOT NULL,
  `Chromosome` VARCHAR(45) NULL,
  `Strand` VARCHAR(45) NULL,
  PRIMARY KEY (`idChromosome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miod`.`ClinicalSignificance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miod`.`ClinicalSignificance` (
  `idClinicalSignificance` INT NOT NULL,
  `Value` VARCHAR(45) NULL,
  PRIMARY KEY (`idClinicalSignificance`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miod`.`Disease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miod`.`Disease` (
  `idDisease` INT NOT NULL,
  `DiseaseName` VARCHAR(45) NULL,
  `idMIM` VARCHAR(45) NULL,
  PRIMARY KEY (`idDisease`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miod`.`Reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miod`.`Reference` (
  `idReference` INT NOT NULL,
  `PMID` TEXT NULL,
  `DB` VARCHAR(45) NULL,
  PRIMARY KEY (`idReference`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miod`.`Microindel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miod`.`Microindel` (
  `idMicroindel` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Start` VARCHAR(45) NULL,
  `End` VARCHAR(45) NULL,
  `Info` TEXT NULL,
  `Gene_idGene` INT NOT NULL,
  `Chromosome_idChromosome` INT NOT NULL,
  PRIMARY KEY (`idMicroindel`, `Gene_idGene`, `Chromosome_idChromosome`),
  INDEX `fk_Microindel_Gene1_idx` (`Gene_idGene` ASC),
  INDEX `fk_Microindel_Chromosome1_idx` (`Chromosome_idChromosome` ASC),
  CONSTRAINT `fk_Microindel_Gene1`
    FOREIGN KEY (`Gene_idGene`)
    REFERENCES `miod`.`Gene` (`idGene`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Microindel_Chromosome1`
    FOREIGN KEY (`Chromosome_idChromosome`)
    REFERENCES `miod`.`Chromosome` (`idChromosome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miod`.`Microindel_has_Reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miod`.`Microindel_has_Reference` (
  `Microindel_idMicroindel` INT NOT NULL,
  `Reference_idReference` INT NOT NULL,
  PRIMARY KEY (`Microindel_idMicroindel`, `Reference_idReference`),
  INDEX `fk_Microindel_has_Reference_Reference1_idx` (`Reference_idReference` ASC),
  INDEX `fk_Microindel_has_Reference_Microindel1_idx` (`Microindel_idMicroindel` ASC),
  CONSTRAINT `fk_Microindel_has_Reference_Microindel1`
    FOREIGN KEY (`Microindel_idMicroindel`)
    REFERENCES `miod`.`Microindel` (`idMicroindel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Microindel_has_Reference_Reference1`
    FOREIGN KEY (`Reference_idReference`)
    REFERENCES `miod`.`Reference` (`idReference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miod`.`Microindel_has_ClinicalSignificance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miod`.`Microindel_has_ClinicalSignificance` (
  `Microindel_idMicroindel` INT NOT NULL,
  `ClinicalSignificance_idClinicalSignificance` INT NOT NULL,
  PRIMARY KEY (`Microindel_idMicroindel`, `ClinicalSignificance_idClinicalSignificance`),
  INDEX `fk_Microindel_has_ClinicalSignificance_ClinicalSignificance_idx` (`ClinicalSignificance_idClinicalSignificance` ASC),
  INDEX `fk_Microindel_has_ClinicalSignificance_Microindel1_idx` (`Microindel_idMicroindel` ASC),
  CONSTRAINT `fk_Microindel_has_ClinicalSignificance_Microindel1`
    FOREIGN KEY (`Microindel_idMicroindel`)
    REFERENCES `miod`.`Microindel` (`idMicroindel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Microindel_has_ClinicalSignificance_ClinicalSignificance1`
    FOREIGN KEY (`ClinicalSignificance_idClinicalSignificance`)
    REFERENCES `miod`.`ClinicalSignificance` (`idClinicalSignificance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miod`.`Microindel_has_Disease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miod`.`Microindel_has_Disease` (
  `Microindel_idMicroindel` INT NOT NULL,
  `Disease_idDisease` INT NOT NULL,
  PRIMARY KEY (`Microindel_idMicroindel`, `Disease_idDisease`),
  INDEX `fk_Microindel_has_Disease_Disease1_idx` (`Disease_idDisease` ASC),
  INDEX `fk_Microindel_has_Disease_Microindel1_idx` (`Microindel_idMicroindel` ASC),
  CONSTRAINT `fk_Microindel_has_Disease_Microindel1`
    FOREIGN KEY (`Microindel_idMicroindel`)
    REFERENCES `miod`.`Microindel` (`idMicroindel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Microindel_has_Disease_Disease1`
    FOREIGN KEY (`Disease_idDisease`)
    REFERENCES `miod`.`Disease` (`idDisease`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

DROP TABLE IF EXISTS `Members`;
/* Create a the members table */
CREATE TABLE miod.Members (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password CHAR(128) NOT NULL
) ENGINE = InnoDB;

DROP TABLE IF EXISTS `Comments`;
/* Create a the members table */
CREATE TABLE miod.Comments (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(50) NOT NULL,
    comment TEXT NOT NULL
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
